apiVersion: v1
kind: Secret
metadata:
  name: platform-org-secrets
  namespace: platform-org
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.secrets.djangoSecretKey }}"
  DATABASE_URL: "{{ .Values.secrets.databaseUrl }}"
  REDIS_URL: "{{ .Values.secrets.redisUrl }}"
  ENTRA_TENANT_ID: "{{ .Values.secrets.entraTenantId }}"
  ENTRA_CLIENT_ID: "{{ .Values.secrets.entraClientId }}"
  ENTRA_ALLOWED_ISSUER: "{{ .Values.secrets.entraAllowedIssuer }}"
  TEAMS_WEBHOOK_URL: "{{ .Values.secrets.teamsWebhookUrl }}"
